---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-auth
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ${AUTHELIA_HTTPROUTE:-${APP}}
  extAuth:
    failOpen: false
    headersToExtAuth:
      - accept
      - cookie
      - authorization
      - proxy-authorization
      - x-forwarded-proto
    http:
      backendRefs:
        - name: authelia
          namespace: auth
          port: 80
      path: /api/authz/ext-authz/
      headersToBackend:
        - remote-*
        - authelia-*