---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: janitorr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: janitorr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # API keys for media services
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        JELLYFIN_API_KEY: "{{ .JELLYFIN_API_KEY }}"
        JELLYFIN_USERNAME: "{{ .JELLYFIN_USERNAME }}"
        JELLYFIN_PASSWORD: "{{ .JELLYFIN_PASSWORD }}"
        JELLYSTAT_API_KEY: "{{ .JELLYSTAT_API_KEY }}"
        JELLYSEERR_API_KEY: "{{ .JELLYSEERR_API_KEY }}"

  dataFrom:
    - extract:
        key: janitorr
