---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./config-generator.yaml
configMapGenerator:
  - name: janitorr-config
    files:
      - application.yml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
