---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app foundry-vtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: foundry-vtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        FOUNDRY_USERNAME: "{{ .foundry_username }}"
        FOUNDRY_PASSWORD: "{{ .foundry_password }}"
        FOUNDRY_ADMIN_KEY: "{{ .foundry_admin_key }}"
        config.json: |
          {
            "foundry_username": "{{ .foundry_username }}",
            "foundry_password": "{{ .foundry_password }}",
            "foundry_admin_key": "{{ .foundry_admin_key }}"
          }
  dataFrom:
    - extract:
        key: *app