---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../../../shared/components/common
resources:
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  #  - ./kromgo/ks.yaml
  - ./victoria-logs/ks.yaml
  - ./victoria-metrics/ks.yaml
