---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "rook-ceph-mon-a-volsync"
  namespace: rook-ceph
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "rook-ceph-mon-a-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "rest:http://restic-rest-nfs.volsync-system.svc.cluster.local:8000/repository/rook-ceph-mon-a"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "rook-ceph-mon-b-volsync"
  namespace: rook-ceph
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "rook-ceph-mon-b-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "rest:http://restic-rest-nfs.volsync-system.svc.cluster.local:8000/repository/rook-ceph-mon-b"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "rook-ceph-mon-c-volsync"
  namespace: rook-ceph
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "rook-ceph-mon-c-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "rest:http://restic-rest-nfs.volsync-system.svc.cluster.local:8000/repository/rook-ceph-mon-c"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-template
