---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia-auth-rules-watcher
  labels:
    app.kubernetes.io/name: authelia-auth-rules-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authelia-auth-rules-watcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authelia-auth-rules-watcher
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      serviceAccountName: authelia-init
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: auth-rules-watcher
          image: ghcr.io/home-operations/k8s-sidecar:2.1.2@sha256:d9e169add4e71fd5931a24e11696853f3d804ebc2022cd81f038e7ef22f4d626
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: NAMESPACE
              value: ALL
            - name: LABEL
              value: "authelia.com/auth-rules"
            - name: LABEL_VALUE
              value: "true"
            - name: FOLDER
              value: "/tmp/auth-rules"
            - name: RESOURCE
              value: "configmap"
            - name: UNIQUE_FILENAMES
              value: "true"
            - name: METHOD
              value: "WATCH"
            - name: SCRIPT
              value: "/scripts/update-auth-rules-configmap.py"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: scripts
          configMap:
            name: authelia-merge-script
            defaultMode: 0755
        - name: tmp
          emptyDir: {}