---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Authelia
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: "uid={{ .LLDAP_LDAP_USER_DN }},ou=people,{{ .LLDAP_LDAP_BASE_DN }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .LLDAP_LDAP_USER_PASS }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: "{{ .LLDAP_LDAP_BASE_DN }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"

        # Other Variables
        JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        SMTP_SENDER: "{{ .SMTP_SENDER }}"

        # OIDC Apps
        # AUTOBRR_OAUTH_CLIENT_ID: "{{ .AUTOBRR_OAUTH_CLIENT_ID }}"
        # AUTOBRR_OAUTH_CLIENT_SECRET: "{{ .AUTOBRR_OAUTH_CLIENT_SECRET_HASH }}"
        # DASHBRR_OAUTH_CLIENT_ID: "{{ .DASHBRR_OAUTH_CLIENT_ID }}"
        # DASHBRR_OAUTH_CLIENT_SECRET: "{{ .DASHBRR_OAUTH_CLIENT_SECRET_HASH }}"
        GRAFANA_OAUTH_CLIENT_ID: "{{ .GRAFANA_OAUTH_CLIENT_ID }}"
        GRAFANA_OAUTH_CLIENT_SECRET_DIGEST: "{{ .GRAFANA_OAUTH_CLIENT_SECRET_DIGEST }}"
        PROXMOX_HOME_OAUTH_CLIENT_ID: "{{ .PROXMOX_HOME_OAUTH_CLIENT_ID }}"
        PROXMOX_HOME_OAUTH_CLIENT_SECRET_DIGEST: "{{ .PROXMOX_HOME_OAUTH_CLIENT_SECRET_DIGEST }}"
        PROXMOX_OBSERVATORY_OAUTH_CLIENT_ID: "{{ .PROXMOX_OBSERVATORY_OAUTH_CLIENT_ID }}"
        PROXMOX_OBSERVATORY_OAUTH_CLIENT_SECRET_DIGEST: "{{ .PROXMOX_OBSERVATORY_OAUTH_CLIENT_SECRET_DIGEST }}"
        HOMEASSISTANT_OAUTH_CLIENT_ID: "{{ .HOMEASSISTANT_OAUTH_CLIENT_ID }}"
        HOMEASSISTANT_OAUTH_CLIENT_SECRET_DIGEST: "{{ .HOMEASSISTANT_OAUTH_CLIENT_SECRET_DIGEST }}"

        # IMMICH_OAUTH_CLIENT_ID: "{{ .IMMICH_OAUTH_CLIENT_ID }}"
        # IMMICH_OAUTH_CLIENT_SECRET: "{{ .IMMICH_OAUTH_CLIENT_SECRET_HASH }}"
        # PAPERLESS_OAUTH_CLIENT_ID: "{{ .PAPERLESS_OAUTH_CLIENT_ID }}"
        # PAPERLESS_OAUTH_CLIENT_SECRET: "{{ .PAPERLESS_OAUTH_CLIENT_SECRET_HASH }}"

  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: lldap
