---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app echo-secure
  namespace: &namespace auth
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: authelia
      namespace: auth
  interval: 30m
  path: ./kubernetes/clusters/home-k3s/apps/auth/echo-secure/app
  postBuild:
    substitute:
      APP: *app
      NS: *namespace
      GATEWAY_DOMAIN: ${DOMAIN}
      GATEWAY_NAME: external
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false