---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${DOMAIN:=domain}
spec:
  secretName: ${DOMAIN:=domain}-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ${DOMAIN}
  dnsNames: ["${DOMAIN}", "*.${DOMAIN}"]
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${INTERNAL_DOMAIN:=internal-domain}
spec:
  secretName: ${INTERNAL_DOMAIN:=internal-domain}-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: ${INTERNAL_DOMAIN}
  dnsNames: ["${INTERNAL_DOMAIN}", "*.${INTERNAL_DOMAIN}"]
