apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: ergoircd-proxy-protocol
  namespace: comms
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: TCPRoute
      name: ergoircd-irc-tls
  proxyProtocol:
    version: V2
