---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app ergoircd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ergoircd
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mariadb_password: "{{ .MARIADB_PASSWORD }}"
        mariadb_root_password: "{{ .MARIADB_ROOT_PASSWORD }}"
        NETWORK_NAME: "{{ .NETWORK_NAME }}"
        OPER_NAME: "{{ .OPER_NAME }}"
        OPER_HASH: "{{ .OPER_HASH }}"
  dataFrom:
    - extract:
        key: *app
