---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - ircd.yaml=./resources/ircd.yaml
    name: ergoircd-config
generatorOptions:
  disableNameSuffixHash: true
resources:
  - backendtrafficpolicy.yaml
  - certificate.yaml
  - externalsecret.yaml
  - helmrelease.yaml
  - mariadb-deployment.yaml
  - mariadb-pvc.yaml
  - mariadb-service.yaml
  - tcproutes.yaml
