---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./metrics-server.yaml
  - ./onepassword.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./rke2.yaml
  - ./rook-ceph.yaml
  - ./spegel.yaml
  - ./stakater.yaml
