---
- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  vars:
    k3s_become: true
  roles:
    - role: ansible-role-k3s
- name: Fetch kubeconfig
  hosts: k3s-bd795-1
  become: true
  tasks:
    - fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env', 'KUBECONFIG') }}"
        flat: "yes"
