---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - ./resources/post-process.sh
      - ./resources/natpmp-manager.sh
      - ./resources/qbittorrent-startup.sh
    name: qbittorrent-scripts
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  disableNameSuffixHash: true
resources:
  - ./helmrelease.yaml
  - ./vmrule.yaml
  - ./ciliumnetworkpolicy.yaml

components:
  - ../../../../../../shared/components/gateway-ext-auth
